### ISSUE TITLE
build with edib on VM hosted in the cloud

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [edib-tool/mix-edib#10]
building using EC2 docker-machine, the `mix edib` start but I have this  message:

```
| Status: Downloaded newer image for edib/edib-tool:1.3.0
| make -f edib/prerequisites.mk
| make[1]: Entering directory '/build'
| ** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available
| rsync -av \
|   --exclude=.git\
|   --exclude=.edib.log \
|   --exclude=_build \
|   --exclude=deps \
|   --exclude=node_modules \
|   --exclude=rel/ \
|   --exclude=tarballs \
|   /source/ /build/app
| sending incremental file list
| ./
| sent 47 bytes  received 19 bytes  132.00 bytes/sec
| total size is 0  speedup is 0.00
```

The problem is the fact who the project is locally stored, and not on my EC2 VM.
Using `docker build .` instruction, before build, it will rsync folder from local to VM folder before build.

Do you think it's possible to improve that ?
I can create a PR for that, but I need help to place a the right place the update.
I think I will create a method `before_run_command` here: https://github.com/edib-tool/mix-edib/blob/master/lib/edib/runner/artifact_builder.ex#L34
to sync local folder with VM.

What do you think ?

**Comment by asaaki** [comment]
I'm not sure if I really understand the issue.

From my understanding the task `mix edib` should be triggered **after** you have checked out your code in your build environment:

```
$ build process in the VM/CI/... starts
$ checkout code (like git clone your-elixir-project-repo)
$ enter the code base directory
$ mix edib
$ store the created docker image into your private docker registry
   or do something with the local tarball artefact
```

So what exactly is different in your case and what kind of changes do you need within _edib_ to get it working?

**Comment by MarcAntoine-Arnaud** [comment]
Sorry to no be really clear.

In fact in this case we have 3 storages:
- local, where I have my elixir project
- vm, the filesystem who host the docker-machine
- the container, where we build the application

And in this case, where the docker-machine is not on the local machine, the mounted volume between the VM filesystem and the container is empty.
As I explain before, the `docker build` command check if the build is local or if it's need to be sync between filesystem before build.

To reproduce the problem you've to do:
- create a docker machine on EC2 VM from your computer
- set the environment for this machine
- run mix edib

**Comment by MarcAntoine-Arnaud** [comment]
I think I found an another issue but related with this one.
Trying to generate the Docker image with a repository cloned into /tmp, the docker volumes are incorrects due to defaults parameters. But the issue comes from Elixir because this command:
`System.cwd!` return `/private/tmp/project_name`.

After that, as the input folder mounted in the docker image is incorrect, the `rsync` is empty, of course !

**Comment by asaaki** [comment]
> `System.cwd!` return `/private/tmp/project_name`

From this line I assume you work with OSX. Elixir does nothing wrong, in fact this is the real location of the `/tmp` (which is just a symlink). This is nothing Elixir or EDIB will fix, since it is pretty usual to resolve symlinks in most cases. (Internally it refers to Erlang's [file:get_cwd/1](http://erlang.org/doc/man/file.html#get_cwd-1), so absolutely nothing we can do right now here.)

My suggestion is to check that the directory you use is not a symlink to another location, to avoid further confusion about weird paths.

> After that, as the input folder mounted in the docker image is incorrect, the rsync is empty, of course !

I think there can be another reason for this issue in general _(`rsync` is empty):_
In case you use Boot2Docker or Docker Toolbox it might be that you can't use any paths outside of `/Users` base directory, because there will be no automatic mount point within the Docker VM.
See: https://github.com/docker/machine/issues/1826, https://github.com/docker/machine/issues/13

I'm currently using the Docker for Mac (public beta), which should not have this issue anymore:
https://docs.docker.com/docker-for-mac/

**Comment by asaaki** [comment]
Regarding the initial issue I'm tempted to say, that this should not be a concern of EDIB, at least for now.

The reason is that I think EDIB should be like a UNIX tool and do one job, and hopefully do this one well.
So any precondition or requirement before a docker image build should be resolved before invoking `mix edib`. Ideally.

Or in other words: any step necessary for a setup should be more explicit. And any step which is not part of the tool's domain should not be included or supported by it.

Since I'm not sure if your reported issue and setup is a common and widely used one, I don't know if it really make sense to investigate further.

This opinion is not fixed and this direction is not set in stone. So if there are convincing reasonings that this should be part of EDIB, I'm willing to reconsider my position.

I hope you can understand my point of view a bit.
I'd like to stabilize the tool first and head to a `1.0.0` release at one point.
Again, if you think this should be part of such release, tell me.
For better testing from my side, a demo repository for the above mentioned setup would be really cool. Something similar along the line of https://github.com/edib-tool/edib-app-test-ci for example, or at least a repo with detailed steps what a user needs to prepare to build an environment like yours.

**Comment by asaaki** [comment]
So, I played a bit with `docker-machine` and `AWS`, but I don't know how the rest of the setup needs to look like. Do I need a dummy `Dockerfile`, so that I can invoke `docker build .`? (Because without a Dockerfile this command does not make sense.)

**Comment by asaaki** [comment]
Okay, after some further testing I'm a bit stuck:
- I created an AWS docker host and got it running.
- I manage to build a docker image with a simple Dockerfile:
  
  ```
  # Dockerfile
  FROM alpine
  COPY . /tmp
  CMD ls -ahlF /tmp
  ```
- After a build the pushed files are immediately deleted again (the docker build context is not preserved), so `mix edib` does not have any files to work with (more specifically any command after a `docker build`).

What do I need to do to preserve the pushed files?
It seems I would need to use something like `docker-machine scp` instead, but that fails do to permission issues.

**Comment by asaaki** [comment]
_Yet Another Status Update_

After realizing, that there is no convenient way to push data to the docker host before any docker command, lots of googling, playing with various docker commands, further googling, stackoverflowing, …, I found a hint which could help: http://stackoverflow.com/a/37123112/653173

``` sh
# answer adjusted for EDIB use case:
docker create \
  --name build_context \
  --volume /source \
  busybox # or a pseudo-scratch container
tar -c -C `pwd` . | docker cp - build_context:/source
docker run \
  --volumes-from build_context \
  … and all the other EDIB settings via `mix edib` …
docker rm build_context # destroy data container after build
```

In words: Instead of directly mounting a (local) directory (which obviously fails for remote docker hosts), we could create a docker volume container with the source code and later mounting it in the edib-tool container as source.
(Haven't tested it yet, but in my head this somehow works.)

To fully verify this approach I'll need some time, since the current volume mounting would become obsolete and would be replaced with the container volumes mounting option.

This would solve your issue, be feasible for all users and use cases, and not require the _pre command_ feature yet.

The `build_context` container will be even more useful than just for the source files, but all other possible locale files someone might want to have within the build process.

---

WDYT?

**Comment by asaaki** [comment]
@MarcAntoine-Arnaud Sorry for the long monologue. 😅 
It just took some time to understand the real problem space.

**Comment by asaaki** [comment]
No active development.
