### ISSUE TITLE
no function clause matching in String.replace_trailing/3

### ISSUE THREAD

**Issue by fazibear** [edib-tool/mix-edib#17]
Exception:

```
| cd /build/app && MIX_ENV=prod mix release
| Building release with MIX_ENV=prod.
|
| You have dependencies (direct/transitive) which are not in :applications!
| The following apps should be added to :applications in mix.exs:
|         edib => edib is missing from taped
| Continue anyway? Your release may not work as expected if these dependencies are required! [Yn]:
| ** (FunctionClauseError) no function clause matching in String.replace_trailing/3
|     (elixir) lib/string.ex:646: String.replace_trailing(:eof, "\n", "")
|     lib/mix/tasks/release.ex:101: Mix.Tasks.Release.check_applications/2
|     lib/mix/tasks/release.ex:72: Mix.Tasks.Release.do_run/1
|     (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| make[2]: *** [edib/make-app.mk:30: /build/app/rel/app/releases/0.0.0/app.tar.gz] Error 1
| make[2]: Leaving directory '/build'
| make[1]: *** [edib/edib.mk:23: app-release] Error 2
| make[1]: Leaving directory '/build'
| make: *** [edib/Makefile:6: edib] Error 2
```

info:

```
==> Creating artifact (might take a while) ...
| make -f edib/prerequisites.mk
| make[1]: Entering directory '/build'
| mix hex.info
| Hex:    0.12.1
| Elixir: 1.3.2
| OTP:    18.3.2
| Built with: Elixir 1.2.5 and OTP 18.3.3
| Registry file available (last updated: 2016-08-26 16:43:31)
```

**Comment by fazibear** [comment]
Hi, any thoughts on that ? Deploy is waiting ;)

**Comment by asaaki** [comment]
Hi @fazibear,

sorry, hadn't time to look into it yet.

So far this looks like you adding `edib` as a mix dependency into your project, which is not necessary, since the preferred usage is to [install edib as an archive](https://github.com/edib-tool/mix-edib#installation) instead, so the only requirement is `exrm` (for now) in the dependeny list of your project.

**Comment by fazibear** [comment]
Thanks, I removed it temporary and it works. The problem is when you have any application that is not included build will break.

**Comment by asaaki** [comment]
> The problem is when you have any application that is not included build will break.

This is in fact an [exrm issue (another example)](https://github.com/bitwalker/exrm/issues/252), so nothing I can fix here.

I will check if a move to [distillery](https://github.com/bitwalker/distillery) makes more sense (probably, because the author created both projects and is in favour of the latter), but in the end people still should take care of the dependencies they include in their projects.

---

Just to make things a bit more clear:
You never need to include `edib` as a dependency in your project, it should always be installed via the `mix archive.install` task.

Example on how to install edib in a CI environment:
https://github.com/edib-tool/edib-app-test-ci/blob/master/Makefile#L23

**Comment by fazibear** [comment]
It might me helpful. If you want to have `edib` in you `mix.exs` you can add it with `warn_missing` parameter:

```
{:edib, "~> 0.8", warn_missing: false}
```

**Comment by asaaki** [comment]
I close this issue, since the solution is to not include `edib` into your project dependencies.

**Comment by fazibear** [comment]
Just like I wrote. You can add it to you project deps with `warn_mssing: false` option.
